name: Rust Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build with Tauri
        run: |
          cd src-tauri
          cargo build --release
